"""Built-in starter curriculum (original content written for Lumora).

Each lesson is structured so the adaptive engine can choose what to show, and it
is also ingested into the RAG vector store as shared learning material.
Question tuple: (prompt, options, correct_index, explanation, hint, difficulty 1-3)
"""

CURRICULUM = [
    {
        "slug": "mathematics", "name": "Mathematics", "icon": "calculator",
        "description": "Numbers, patterns and shapes - puzzles that train your thinking.",
        "course": {"slug": "math-foundations", "title": "Math Foundations", "description": "Core number sense and geometry."},
        "topics": [
            {
                "slug": "fractions", "title": "Fractions", "icon": "pie-chart",
                "summary": "Understand parts of a whole and compare fractions.",
                "lesson": {
                    "title": "Fractions: Sharing Things Fairly",
                    "key_idea": "A fraction shows how many equal parts of a whole you have. The bottom number (denominator) tells how many equal parts the whole is cut into. The top number (numerator) tells how many of those parts you have.",
                    "steps": [
                        "Look at the bottom number: it tells you how many equal pieces the whole is split into.",
                        "Look at the top number: it tells you how many of those pieces you are talking about.",
                        "Check the pieces are equal in size - fractions only work with equal parts.",
                        "To compare fractions with the same bottom number, the bigger top number is the bigger fraction.",
                    ],
                    "examples": [
                        "A pizza cut into 8 equal slices: if you eat 3 slices, you ate 3/8 of the pizza.",
                        "1/2 of a chocolate bar is the same amount as 2/4 of the same bar - these are equivalent fractions.",
                        "3/5 is bigger than 2/5 because both are fifths and 3 pieces is more than 2 pieces.",
                    ],
                    "analogy": "Imagine sharing a cake with friends. The denominator is how many friends share it, and the numerator is how many slices you get.",
                    "summary": "Fractions describe equal parts of a whole. Denominator = number of equal parts; numerator = parts you have. Equivalent fractions name the same amount.",
                    "vocabulary": [["numerator", "the top number - parts you have"], ["denominator", "the bottom number - total equal parts"], ["equivalent", "worth the same amount"]],
                    "fun_fact": "The word 'fraction' comes from the Latin word 'fractus', which means 'broken'.",
                },
                "questions": [
                    ("A pizza is cut into 4 equal slices. You eat 1 slice. What fraction did you eat?", ["1/4", "4/1", "1/2", "3/4"], 0, "There are 4 equal slices and you ate 1, so it's 1 out of 4: 1/4.", "Count all the slices first. That number goes on the bottom.", 1),
                    ("In the fraction 3/7, what does the 7 tell you?", ["How many parts you have", "How many equal parts the whole is split into", "How many wholes there are", "The answer to 3 + 4"], 1, "The bottom number (denominator) is how many equal parts the whole is cut into.", "Is 7 on the top or the bottom?", 1),
                    ("Which fraction is bigger: 2/6 or 5/6?", ["2/6", "5/6", "They are equal", "You can't tell"], 1, "Both are sixths, so compare the top numbers: 5 is more than 2.", "The bottom numbers match - so look at the tops.", 2),
                    ("Which fraction is equivalent to 1/2?", ["2/3", "3/6", "1/4", "2/5"], 1, "3/6 means 3 out of 6 equal parts - that's exactly half.", "Is the top number exactly half of the bottom number?", 2),
                    ("Which is bigger: 1/3 or 1/5?", ["1/3", "1/5", "They are equal", "It depends on the pizza"], 0, "Cutting a whole into 3 parts makes bigger pieces than cutting it into 5 parts.", "Would you rather share a cake with 3 people or 5 people?", 3),
                    ("What is 2/8 written in its simplest form?", ["1/4", "2/4", "1/6", "4/8"], 0, "Divide top and bottom by 2: 2 ÷ 2 = 1 and 8 ÷ 2 = 4, so 2/8 = 1/4.", "What number divides both 2 and 8 evenly?", 3),
                ],
            },
            {
                "slug": "multiplication", "title": "Multiplication", "icon": "x",
                "summary": "See multiplication as equal groups and arrays.",
                "lesson": {
                    "title": "Multiplication: Super-Fast Adding",
                    "key_idea": "Multiplication is a quick way to add equal groups. 4 × 3 means 4 groups of 3, which is 3 + 3 + 3 + 3 = 12.",
                    "steps": [
                        "Read the first number as 'how many groups'.",
                        "Read the second number as 'how many in each group'.",
                        "Draw or imagine the groups, or make an array of rows and columns.",
                        "Count or skip-count to find the total.",
                    ],
                    "examples": [
                        "3 bags with 5 apples each: 3 × 5 = 15 apples.",
                        "An egg box with 2 rows of 6 eggs: 2 × 6 = 12 eggs.",
                        "Skip-count by 4 three times: 4, 8, 12 - so 3 × 4 = 12.",
                    ],
                    "analogy": "Multiplication is like a shortcut on a map: instead of walking 3 + 3 + 3 + 3, you jump straight to 12.",
                    "summary": "Multiplication means equal groups. The order doesn't change the answer: 3 × 4 = 4 × 3.",
                    "vocabulary": [["product", "the answer to a multiplication"], ["array", "objects arranged in rows and columns"], ["factor", "a number being multiplied"]],
                    "fun_fact": "Any number multiplied by 0 is 0 - because zero groups of anything is nothing!",
                },
                "questions": [
                    ("What is 2 × 5?", ["7", "10", "25", "3"], 1, "2 groups of 5 is 5 + 5 = 10.", "Try adding 5 two times.", 1),
                    ("Which addition matches 3 × 4?", ["3 + 4", "4 + 4 + 4", "3 + 3", "4 + 3 + 4 + 3"], 1, "3 × 4 means 3 groups of 4: 4 + 4 + 4.", "How many groups? How many in each?", 1),
                    ("A garden has 4 rows of 6 flowers. How many flowers?", ["10", "24", "20", "18"], 1, "4 rows × 6 flowers = 24 flowers.", "Skip-count by 6, four times.", 2),
                    ("What is 7 × 3?", ["21", "10", "24", "17"], 0, "7 groups of 3: 3, 6, 9, 12, 15, 18, 21.", "Skip-count by 3 seven times.", 2),
                    ("If 6 × 8 = 48, what is 8 × 6?", ["14", "86", "48", "56"], 2, "Order doesn't matter in multiplication, so 8 × 6 = 48 too.", "Does swapping the numbers change the total?", 3),
                    ("Tickets cost 9 coins each. How much for 7 tickets?", ["56", "63", "72", "16"], 1, "7 × 9 = 63 coins.", "Try 7 × 10, then take away one 7.", 3),
                ],
            },
            {
                "slug": "shapes-geometry", "title": "Shapes & Geometry", "icon": "shapes",
                "summary": "Name 2D shapes, count sides and corners, find symmetry.",
                "lesson": {
                    "title": "Shapes All Around Us",
                    "key_idea": "2D shapes are flat. We can describe them by counting their sides (straight edges) and vertices (corners).",
                    "steps": [
                        "Trace around the shape with your finger.",
                        "Count each straight side as you go.",
                        "Count the corners where two sides meet - these are vertices.",
                        "Use the count to name it: 3 sides = triangle, 4 = quadrilateral, 5 = pentagon, 6 = hexagon.",
                    ],
                    "examples": [
                        "A triangle has 3 sides and 3 vertices - like a slice of pizza.",
                        "A square has 4 equal sides and 4 right-angle corners - like a window pane.",
                        "A hexagon has 6 sides - honeybees build hexagon-shaped cells.",
                    ],
                    "analogy": "Counting sides is like walking around a playground fence: each straight bit of fence is a side, and each place you turn is a corner.",
                    "summary": "Describe shapes by sides and vertices. A line of symmetry splits a shape into two mirror-image halves.",
                    "vocabulary": [["vertex", "a corner where sides meet (plural: vertices)"], ["symmetry", "both halves match like a mirror"], ["quadrilateral", "any shape with 4 sides"]],
                    "fun_fact": "A circle has no straight sides and no corners at all!",
                },
                "questions": [
                    ("How many sides does a triangle have?", ["2", "3", "4", "5"], 1, "'Tri' means three - a triangle has 3 sides.", "Think of 'tricycle' - how many wheels?", 1),
                    ("Which shape has 4 equal sides and 4 square corners?", ["Rectangle", "Triangle", "Square", "Circle"], 2, "A square has 4 equal sides and 4 right angles.", "All the sides are the same length.", 1),
                    ("How many vertices does a pentagon have?", ["4", "5", "6", "8"], 1, "A pentagon has 5 sides and 5 vertices.", "A shape has the same number of corners as sides.", 2),
                    ("Which shape do honeybees use to build their honeycomb cells?", ["Hexagon", "Square", "Circle", "Triangle"], 0, "Honeycomb cells are hexagons - 6-sided shapes that fit together with no gaps.", "It has 6 sides.", 2),
                    ("How many lines of symmetry does a square have?", ["1", "2", "4", "0"], 2, "A square has 4: up-down, left-right and both diagonals.", "Don't forget the diagonal lines!", 3),
                    ("A shape has 8 sides. What is it called?", ["Hexagon", "Octagon", "Pentagon", "Decagon"], 1, "'Octo' means eight - like an octopus with 8 arms.", "Think of an octopus.", 3),
                ],
            },
        ],
    },
    {
        "slug": "science", "name": "Science", "icon": "flask",
        "description": "Explore living things, Earth and space through curious questions.",
        "course": {"slug": "science-explorers", "title": "Science Explorers", "description": "Life, Earth and space science."},
        "topics": [
            {
                "slug": "plants-photosynthesis", "title": "How Plants Make Food", "icon": "sprout",
                "summary": "Discover photosynthesis: sunlight, water and air become food.",
                "lesson": {
                    "title": "Photosynthesis: A Plant's Kitchen",
                    "key_idea": "Plants make their own food through photosynthesis. Their leaves use sunlight to turn water and carbon dioxide (a gas in the air) into sugar for energy, and they release oxygen.",
                    "steps": [
                        "Roots soak up water from the soil.",
                        "Tiny holes in leaves take in carbon dioxide from the air.",
                        "Chlorophyll, the green substance in leaves, captures sunlight energy.",
                        "The plant uses that energy to make sugar (food) and gives out oxygen.",
                    ],
                    "examples": [
                        "A plant kept in a dark cupboard turns pale and weak because it can't make enough food.",
                        "The oxygen we breathe comes largely from plants and tiny ocean algae doing photosynthesis.",
                        "Leaves are flat and wide so they can catch as much sunlight as possible.",
                    ],
                    "analogy": "A leaf is like a solar-powered kitchen: sunlight is the electricity, water and air are the ingredients, and sugar is the meal.",
                    "summary": "Photosynthesis: sunlight + water + carbon dioxide -> sugar + oxygen. It happens in leaves thanks to green chlorophyll.",
                    "vocabulary": [["photosynthesis", "how plants make food using light"], ["chlorophyll", "the green substance that captures sunlight"], ["carbon dioxide", "a gas in the air that plants use"]],
                    "fun_fact": "'Photo' means light and 'synthesis' means putting together - so photosynthesis means 'putting together with light'.",
                },
                "questions": [
                    ("What do plants need from the Sun to make food?", ["Heat only", "Light", "Wind", "Rain"], 1, "Plants capture sunlight energy to make food.", "Photo- means...?", 1),
                    ("Which gas do plants give out during photosynthesis?", ["Carbon dioxide", "Oxygen", "Smoke", "Helium"], 1, "Plants release oxygen - the gas we need to breathe.", "It's the gas you breathe in.", 1),
                    ("What makes leaves green?", ["Water", "Chlorophyll", "Soil", "Sugar"], 1, "Chlorophyll is green and captures sunlight.", "It's the special substance that catches light.", 2),
                    ("Which part of the plant takes in water from the soil?", ["Leaves", "Flowers", "Roots", "Petals"], 2, "Roots soak up water from the soil.", "Which part is underground?", 2),
                    ("Why might a plant in a dark cupboard grow weak?", ["It is too cold", "It can't make enough food without light", "It has too much water", "Cupboards are too small"], 1, "Without light, photosynthesis can't happen, so the plant can't make food.", "What does photosynthesis need?", 3),
                    ("Which is the correct 'recipe' for photosynthesis?", ["Oxygen + sugar -> water", "Sunlight + water + carbon dioxide -> sugar + oxygen", "Soil + rain -> leaves", "Sugar + light -> carbon dioxide"], 1, "Plants combine water and carbon dioxide using light to make sugar and oxygen.", "Ingredients: light, water and a gas from the air.", 3),
                ],
            },
            {
                "slug": "water-cycle", "title": "The Water Cycle", "icon": "droplets",
                "summary": "Follow water as it evaporates, condenses and falls as rain.",
                "lesson": {
                    "title": "The Never-Ending Journey of Water",
                    "key_idea": "Water on Earth keeps moving in a loop called the water cycle. It evaporates, condenses into clouds, falls as precipitation, and collects again.",
                    "steps": [
                        "Evaporation: the Sun warms water in seas and lakes, turning it into invisible water vapour.",
                        "Condensation: high in the sky the vapour cools and forms tiny droplets that make clouds.",
                        "Precipitation: droplets join together and fall as rain, snow, sleet or hail.",
                        "Collection: water gathers in rivers, lakes, oceans and underground, then the cycle repeats.",
                    ],
                    "examples": [
                        "A puddle disappears on a sunny day because the water evaporates.",
                        "Drops form on a cold glass of juice - that's condensation.",
                        "Snow melting in spring flows into rivers - that's collection.",
                    ],
                    "analogy": "The water cycle is like a giant recycling machine: the same water gets used again and again - the water you drink today might once have been drunk by a dinosaur!",
                    "summary": "Evaporation -> condensation -> precipitation -> collection, powered by the Sun.",
                    "vocabulary": [["evaporation", "liquid turning into gas"], ["condensation", "gas cooling into liquid droplets"], ["precipitation", "water falling from clouds"]],
                    "fun_fact": "There is about the same amount of water on Earth today as there was millions of years ago.",
                },
                "questions": [
                    ("What do we call water falling from clouds as rain or snow?", ["Evaporation", "Precipitation", "Condensation", "Collection"], 1, "Rain, snow, sleet and hail are all precipitation.", "It starts with 'pre'.", 1),
                    ("What powers the water cycle?", ["The Moon", "The Sun", "Wind turbines", "Fish"], 1, "The Sun's heat makes water evaporate and keeps the cycle going.", "What warms up puddles?", 1),
                    ("Water drops appear on a cold glass. What is this?", ["Evaporation", "Condensation", "Precipitation", "Melting"], 1, "Water vapour in the air cools on the glass and turns back to liquid - condensation.", "Vapour is turning back into liquid.", 2),
                    ("What are clouds made of?", ["Cotton", "Smoke", "Tiny water droplets or ice crystals", "Air only"], 2, "Clouds form when vapour condenses into tiny droplets or ice crystals.", "Think about condensation.", 2),
                    ("Put these in order: condensation, evaporation, precipitation", ["Precipitation, condensation, evaporation", "Evaporation, condensation, precipitation", "Condensation, evaporation, precipitation", "Evaporation, precipitation, condensation"], 1, "Water evaporates, condenses into clouds, then falls as precipitation.", "Water has to go up before it can come down.", 3),
                    ("Why does a puddle dry up faster on a hot day?", ["Heat speeds up evaporation", "Hot days have more rain", "Puddles sink into clouds", "Heat makes condensation"], 0, "More heat gives water more energy to evaporate quickly.", "Which step is helped by warmth?", 3),
                ],
            },
            {
                "slug": "solar-system", "title": "Our Solar System", "icon": "orbit",
                "summary": "Meet the Sun, eight planets and what makes each special.",
                "lesson": {
                    "title": "A Tour of the Solar System",
                    "key_idea": "Our solar system is the Sun and everything that orbits it, including eight planets. The Sun is a star whose gravity keeps the planets moving in paths called orbits.",
                    "steps": [
                        "The Sun sits in the centre - it is a star made of hot glowing gas.",
                        "The four inner planets (Mercury, Venus, Earth, Mars) are small and rocky.",
                        "The four outer planets (Jupiter, Saturn, Uranus, Neptune) are giant planets made mostly of gas or ice.",
                        "Each planet travels around the Sun in its own orbit; one trip is that planet's year.",
                    ],
                    "examples": [
                        "Earth takes about 365 days to orbit the Sun - that's one year.",
                        "Jupiter is the biggest planet; more than 1,000 Earths could fit inside it.",
                        "Saturn is famous for its bright rings made of ice and rock.",
                    ],
                    "analogy": "The solar system is like children on a roundabout holding onto ropes tied to the centre pole - the Sun's gravity is the rope keeping each planet circling.",
                    "summary": "Sun at the centre, 4 rocky inner planets, 4 giant outer planets, all held in orbit by gravity.",
                    "vocabulary": [["orbit", "the path one object takes around another"], ["gravity", "a pulling force"], ["star", "a huge ball of hot glowing gas"]],
                    "fun_fact": "A day on Venus is longer than its year!",
                },
                "questions": [
                    ("What is at the centre of our solar system?", ["Earth", "The Moon", "The Sun", "Jupiter"], 2, "The Sun is at the centre, and the planets orbit it.", "It's a star.", 1),
                    ("How many planets are in our solar system?", ["7", "8", "9", "10"], 1, "There are eight planets.", "Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune.", 1),
                    ("Which is the largest planet?", ["Saturn", "Earth", "Jupiter", "Neptune"], 2, "Jupiter is the biggest planet in our solar system.", "It's a gas giant named after a king of the Roman gods.", 2),
                    ("What keeps the planets in orbit around the Sun?", ["Wind", "Gravity", "Magnets", "Light"], 1, "The Sun's gravity pulls on the planets and keeps them in orbit.", "It's the same force that makes things fall.", 2),
                    ("Which planets are rocky?", ["Jupiter and Saturn", "Mercury, Venus, Earth and Mars", "Uranus and Neptune", "All of them"], 1, "The four inner planets are small and rocky.", "The rocky ones are closest to the Sun.", 3),
                    ("What does 'one year' mean for a planet?", ["One spin on its axis", "One trip around the Sun", "One trip around its moon", "365 days on every planet"], 1, "A planet's year is the time it takes to orbit the Sun once.", "Think about Earth's 365-day journey.", 3),
                ],
            },
        ],
    },
    {
        "slug": "reading", "name": "Reading", "icon": "book-open",
        "description": "Build confident reading - main ideas, new words and great stories.",
        "course": {"slug": "reading-adventures", "title": "Reading Adventures", "description": "Comprehension and vocabulary skills."},
        "topics": [
            {
                "slug": "main-idea", "title": "Finding the Main Idea", "icon": "lightbulb",
                "summary": "Spot what a paragraph is mostly about.",
                "lesson": {
                    "title": "The Main Idea: What's It Mostly About?",
                    "key_idea": "The main idea is the most important point the writer wants you to know. Supporting details are the smaller facts that explain or prove the main idea.",
                    "steps": [
                        "Read the whole paragraph once, all the way through.",
                        "Ask: who or what is this mostly about?",
                        "Ask: what is the writer telling me about it?",
                        "Check that most of the sentences support your answer - if they do, you've found the main idea.",
                    ],
                    "examples": [
                        "'Dogs make great pets. They are loyal, playful and love walks.' Main idea: dogs make great pets.",
                        "A paragraph about penguins sliding, swimming and diving: main idea - penguins move in amazing ways.",
                        "The title of a text often gives a clue to the main idea.",
                    ],
                    "analogy": "The main idea is like the roof of a house, and the supporting details are the walls holding it up.",
                    "summary": "Main idea = the big point. Details = the facts that hold it up. Often found in the first or last sentence.",
                    "vocabulary": [["main idea", "the most important point"], ["supporting detail", "a fact that explains the main idea"], ["summary", "a short retelling of the big points"]],
                    "fun_fact": "Many news articles put the main idea in the very first sentence so readers get it quickly.",
                },
                "questions": [
                    ("What is the main idea of a paragraph?", ["The longest sentence", "The most important point", "The last word", "A tiny detail"], 1, "The main idea is the most important point the writer wants you to know.", "Think 'big picture'.", 1),
                    ("'Bees are busy insects. They collect nectar, make honey and help flowers grow.' What is the main idea?", ["Bees make honey", "Bees are busy insects", "Flowers grow", "Nectar is sweet"], 1, "The other sentences explain how bees are busy.", "Which sentence do the others support?", 1),
                    ("What do supporting details do?", ["Change the topic", "Explain or prove the main idea", "End the story", "Ask questions"], 1, "Details back up the main idea with facts and examples.", "They hold up the 'roof'.", 2),
                    ("Where is the main idea often found?", ["In the first or last sentence", "Only in the middle", "In the page number", "Never in the text"], 0, "Writers often state the main idea at the start or end of a paragraph.", "Check the beginning and the end.", 2),
                    ("'Rainforests are home to millions of species. Jaguars hunt there, frogs live in the trees, and new insects are found every year.' Best main idea?", ["Jaguars are fast", "Rainforests are full of different living things", "Frogs live in trees", "Insects are small"], 1, "All the details show how many kinds of living things are in rainforests.", "Which answer covers ALL the details?", 3),
                    ("Which is a supporting detail, not a main idea?", ["Exercise keeps us healthy", "Running makes your heart stronger", "Healthy habits matter", "Our bodies need care"], 1, "'Running makes your heart stronger' is one specific fact.", "Which one is a small, specific fact?", 3),
                ],
            },
            {
                "slug": "context-clues", "title": "New Words & Context Clues", "icon": "search",
                "summary": "Work out tricky words using the words around them.",
                "lesson": {
                    "title": "Word Detective: Using Context Clues",
                    "key_idea": "When you meet a word you don't know, the sentences around it often give clues to its meaning. These are called context clues.",
                    "steps": [
                        "Stop when you reach the tricky word.",
                        "Re-read the sentence and the ones before and after it.",
                        "Look for clues: a definition, an example, a synonym (same meaning) or an antonym (opposite).",
                        "Guess the meaning, then put your guess in place of the word - does the sentence still make sense?",
                    ],
                    "examples": [
                        "'The puppy was famished - it hadn't eaten all day.' Famished means very hungry.",
                        "'Unlike his timid sister, Sam was bold.' Timid is the opposite of bold, so it means shy.",
                        "'She found a gem, a precious stone, in the cave.' The definition is right there!",
                    ],
                    "analogy": "Context clues are like footprints - you can't see the animal, but the tracks around it tell you what it is.",
                    "summary": "Use definitions, examples, synonyms and antonyms nearby to work out new words. Test your guess in the sentence.",
                    "vocabulary": [["context", "the words and sentences around a word"], ["synonym", "a word with the same meaning"], ["antonym", "a word with the opposite meaning"]],
                    "fun_fact": "English has more than 170,000 words in use - nobody knows them all, so everyone uses context clues!",
                },
                "questions": [
                    ("What are context clues?", ["Pictures only", "Hints from nearby words that explain a tricky word", "The page number", "Spelling rules"], 1, "Context clues are hints in the surrounding text.", "Think like a word detective.", 1),
                    ("'The soup was scalding, so hot it burned my tongue.' What does scalding mean?", ["Very cold", "Very hot", "Tasty", "Salty"], 1, "'So hot it burned my tongue' tells us scalding means very hot.", "Read the words right after 'scalding'.", 1),
                    ("'Unlike the noisy classroom, the library was tranquil.' Tranquil means...", ["Loud", "Calm and quiet", "Crowded", "Messy"], 1, "'Unlike noisy' signals the opposite - calm and quiet.", "'Unlike' means the opposite is coming.", 2),
                    ("What is a synonym?", ["A word with the opposite meaning", "A word with the same or similar meaning", "A rhyming word", "A long word"], 1, "Synonyms have the same or similar meanings, like big and large.", "'Syn' means together or same.", 2),
                    ("'After the long hike, Maya was exhausted and could barely keep her eyes open.' Exhausted means...", ["Excited", "Very tired", "Hungry", "Angry"], 1, "Barely keeping eyes open after a long hike shows she was very tired.", "What happens to you after a long walk?", 3),
                    ("'The ancient castle, built over 900 years ago, was crumbling.' Which clue explains 'ancient'?", ["Castle", "Built over 900 years ago", "Crumbling", "The"], 1, "'Built over 900 years ago' tells us ancient means very old.", "Which words tell you about its age?", 3),
                ],
            },
            {
                "slug": "story-elements", "title": "Story Elements", "icon": "scroll",
                "summary": "Characters, setting, problem and solution.",
                "lesson": {
                    "title": "The Building Blocks of a Story",
                    "key_idea": "Most stories are built from the same parts: characters (who), setting (where and when), a problem (what goes wrong) and a solution (how it gets fixed).",
                    "steps": [
                        "Find the characters: who is the story about?",
                        "Find the setting: where and when does it happen?",
                        "Find the problem: what challenge do the characters face?",
                        "Find the solution: how is the problem solved by the end?",
                    ],
                    "examples": [
                        "In 'Goldilocks and the Three Bears', the setting is the bears' house in the woods.",
                        "A story where a girl loses her kite (problem) and her friend helps climb the tree to get it (solution).",
                        "The main character is usually the one the story follows most closely.",
                    ],
                    "analogy": "A story is like a recipe: characters, setting, problem and solution are the ingredients you need for it to work.",
                    "summary": "Characters, setting, problem, solution - the four building blocks of most stories.",
                    "vocabulary": [["character", "a person or animal in a story"], ["setting", "where and when a story happens"], ["plot", "the events of a story in order"]],
                    "fun_fact": "Some of the oldest stories ever found were written down on clay tablets over 4,000 years ago.",
                },
                "questions": [
                    ("What is the setting of a story?", ["Who is in it", "Where and when it happens", "How it ends", "The title"], 1, "The setting tells you where and when the story takes place.", "Think about place and time.", 1),
                    ("Who are the characters in a story?", ["The people or animals in it", "The pages", "The setting", "The author only"], 0, "Characters are the people, animals or creatures in the story.", "Who does things in the story?", 1),
                    ("A dragon is scaring a village. This is the story's...", ["Setting", "Problem", "Solution", "Title"], 1, "The scary dragon is the challenge the characters must face - the problem.", "What has gone wrong?", 2),
                    ("The children build a giant kite to carry the dragon away. This is the...", ["Problem", "Setting", "Solution", "Character"], 2, "Building the kite fixes the problem, so it's the solution.", "How is the trouble fixed?", 2),
                    ("'On a frosty morning in a tiny mountain village...' This sentence tells you the...", ["Solution", "Setting", "Problem", "Main character"], 1, "It tells us when (a frosty morning) and where (a mountain village).", "Does it tell you a place or a time?", 3),
                    ("Why do stories usually need a problem?", ["To make the story longer", "So characters have something to solve, which keeps readers interested", "Because every story has dragons", "To introduce the setting"], 1, "A problem creates a challenge, making us want to read on to see what happens.", "What makes you want to keep reading?", 3),
                ],
            },
        ],
    },
    {
        "slug": "history", "name": "History", "icon": "landmark",
        "description": "Travel through time to meet ancient civilisations and great inventions.",
        "course": {"slug": "time-travellers", "title": "Time Travellers", "description": "Ancient civilisations and how ideas changed the world."},
        "topics": [
            {
                "slug": "ancient-egypt", "title": "Ancient Egypt", "icon": "pyramid",
                "summary": "Pyramids, pharaohs and life along the river Nile.",
                "lesson": {
                    "title": "Ancient Egypt: Gift of the Nile",
                    "key_idea": "Ancient Egypt grew up along the river Nile about 5,000 years ago. The Nile's yearly floods left rich soil for farming, which helped a powerful civilisation ruled by pharaohs to grow.",
                    "steps": [
                        "The Nile flooded every year, spreading fertile black soil on its banks.",
                        "Farmers grew wheat and barley, so there was plenty of food.",
                        "Pharaohs (kings and queens) ruled and were believed to be very special leaders.",
                        "Egyptians built great pyramids as tombs and wrote using picture symbols called hieroglyphs.",
                    ],
                    "examples": [
                        "The Great Pyramid of Giza was built for the pharaoh Khufu about 4,500 years ago.",
                        "Hieroglyphs could be written on papyrus, a paper made from river reeds.",
                        "The Rosetta Stone helped people learn to read hieroglyphs again in the 1800s.",
                    ],
                    "analogy": "The Nile was like a giant delivery truck that brought fresh, rich soil to farmers every single year.",
                    "summary": "The Nile made farming possible; pharaohs ruled; pyramids and hieroglyphs are famous Egyptian achievements.",
                    "vocabulary": [["pharaoh", "a ruler of ancient Egypt"], ["hieroglyphs", "picture writing"], ["papyrus", "paper made from reeds"]],
                    "fun_fact": "Ancient Egyptians invented an early kind of toothpaste!",
                },
                "questions": [
                    ("Which river was ancient Egypt built along?", ["The Amazon", "The Nile", "The Thames", "The Ganges"], 1, "Ancient Egypt grew along the river Nile.", "It's the river with yearly floods.", 1),
                    ("What were the rulers of ancient Egypt called?", ["Emperors", "Pharaohs", "Presidents", "Knights"], 1, "Egypt's rulers were called pharaohs.", "It starts with 'ph'.", 1),
                    ("Why were the Nile floods helpful?", ["They washed houses away", "They left rich soil for farming", "They made the water salty", "They kept enemies away"], 1, "Floods spread fertile soil, so crops grew well.", "Think about what farmers need.", 2),
                    ("What are hieroglyphs?", ["Egyptian boats", "Picture symbols used for writing", "Pyramids", "Types of food"], 1, "Hieroglyphs are Egypt's picture-writing system.", "It's a way of writing.", 2),
                    ("Why were the pyramids built?", ["As shopping centres", "As tombs for pharaohs", "As schools", "As lighthouses"], 1, "Pyramids were tombs to protect pharaohs in the afterlife.", "They are connected to what happened after a pharaoh died.", 3),
                    ("What helped people learn to read hieroglyphs again in the 1800s?", ["The Rosetta Stone", "The Great Wall", "A pyramid map", "The Nile River"], 0, "The Rosetta Stone had the same text in three scripts, which unlocked hieroglyphs.", "It is a famous stone with writing on it.", 3),
                ],
            },
            {
                "slug": "indus-valley", "title": "Indus Valley Civilisation", "icon": "building",
                "summary": "Planned cities, drains and trade in one of the first civilisations.",
                "lesson": {
                    "title": "The Indus Valley: Cities Ahead of Their Time",
                    "key_idea": "Around 4,500 years ago, the Indus Valley Civilisation grew along the Indus river in what is now Pakistan and north-west India. Its cities, like Harappa and Mohenjo-daro, were carefully planned with straight streets and covered drains.",
                    "steps": [
                        "People settled near the Indus river, where floods made the land good for farming.",
                        "They built cities on a grid pattern, with streets crossing at right angles.",
                        "Houses used baked bricks of standard sizes, and many had bathrooms connected to drains.",
                        "They traded goods like beads, cotton and pottery with faraway places.",
                    ],
                    "examples": [
                        "Mohenjo-daro had a 'Great Bath', a large public pool made watertight with bricks and tar.",
                        "Indus people used standard weights, which made trading fair.",
                        "They made seals carved with animals and a script that nobody has fully decoded yet.",
                    ],
                    "analogy": "An Indus city was like a well-organised board game: every street and brick followed the same rules, so everything fitted together neatly.",
                    "summary": "Planned grid cities, brick houses, covered drains, standard weights and long-distance trade.",
                    "vocabulary": [["civilisation", "a large, organised society with cities"], ["drain", "a channel that carries away waste water"], ["trade", "exchanging goods"]],
                    "fun_fact": "The Indus script is still a mystery - experts are still trying to read it today.",
                },
                "questions": [
                    ("Which river was the Indus Valley Civilisation built along?", ["The Nile", "The Indus", "The Yangtze", "The Danube"], 1, "It was named after the Indus river.", "The answer is in the name!", 1),
                    ("Name a famous Indus Valley city.", ["Rome", "Mohenjo-daro", "Athens", "Cairo"], 1, "Mohenjo-daro and Harappa were major Indus cities.", "It's a long name with a hyphen.", 1),
                    ("What was special about Indus city streets?", ["They were made of gold", "They were planned in a grid pattern", "They were all curved", "There were no streets"], 1, "Streets crossed at right angles in a neat grid.", "Think of a chessboard.", 2),
                    ("What did many Indus houses have that was unusual for the time?", ["Electricity", "Bathrooms connected to drains", "Glass windows", "Lifts"], 1, "Many homes had bathrooms linked to covered drains.", "It's to do with keeping clean.", 2),
                    ("Why were standard weights useful for Indus traders?", ["They made trading fair", "They were pretty", "They were used as money only", "They kept boats steady"], 0, "If everyone uses the same weights, trades are fair.", "Imagine buying sweets with a different scale at each shop.", 3),
                    ("What is still a mystery about the Indus Valley Civilisation?", ["Where it was", "Its script has not been fully decoded", "Whether it had cities", "What bricks are"], 1, "Nobody has fully deciphered the Indus script yet.", "Think about the writing on their seals.", 3),
                ],
            },
            {
                "slug": "inventions", "title": "Inventions That Changed the World", "icon": "cog",
                "summary": "The wheel, printing press and more - and why they mattered.",
                "lesson": {
                    "title": "Big Ideas: Inventions That Changed Everything",
                    "key_idea": "Inventions are new tools or ideas that solve problems. Some, like the wheel, the printing press and electricity, changed how everyone lives.",
                    "steps": [
                        "Spot the problem people had (for example, moving heavy things or sharing information).",
                        "Look at the invention that solved it.",
                        "Think about who it helped and how life changed.",
                        "Notice how one invention often led to many more.",
                    ],
                    "examples": [
                        "The wheel (about 5,500 years ago) made carts and pottery wheels possible.",
                        "The printing press (Johannes Gutenberg, about 1440) made books faster and cheaper to produce.",
                        "The telephone (patented in 1876) let people talk across long distances.",
                    ],
                    "analogy": "Inventions are like stepping stones across a river - each one lets people reach the next big idea.",
                    "summary": "Inventions solve problems and build on each other: wheel, printing press, telephone, electricity, computers.",
                    "vocabulary": [["invention", "a new thing or idea that solves a problem"], ["inventor", "a person who creates an invention"], ["patent", "an official record of who invented something"]],
                    "fun_fact": "The first wheels were probably used for making pottery, not for transport!",
                },
                "questions": [
                    ("What is an invention?", ["A type of food", "A new tool or idea that solves a problem", "An old story", "A kind of animal"], 1, "Inventions are new tools or ideas that solve problems.", "Inventors create them.", 1),
                    ("Which invention made carts easier to move?", ["The wheel", "The telephone", "The pencil", "The clock"], 0, "The wheel made moving heavy loads much easier.", "It's round!", 1),
                    ("What did the printing press make easier?", ["Cooking food", "Making many copies of books", "Flying", "Farming"], 1, "The printing press made books faster and cheaper to produce.", "It's about books.", 2),
                    ("Who is known for the printing press around 1440?", ["Isaac Newton", "Johannes Gutenberg", "Marie Curie", "Leonardo da Vinci"], 1, "Johannes Gutenberg built a famous printing press around 1440.", "His name starts with G.", 2),
                    ("Why did the printing press help more people learn to read?", ["Books became cheaper and more common", "It taught reading by itself", "It closed schools", "It made books heavier"], 0, "More, cheaper books meant more people could own and read them.", "Think about cost and how many books existed.", 3),
                    ("What were the first wheels probably used for?", ["Racing cars", "Making pottery", "Bicycles", "Clocks"], 1, "Early wheels were likely potter's wheels before they were used on carts.", "Think about shaping clay.", 3),
                ],
            },
        ],
    },
]
